name: Build Android

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential pkg-config autoconf automake libtool libtool-bin nasm yasm git make golang libasound2-dev

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3
        with:
          cmd-line-tools-version: 11.0

      # Install the exact NDK version required by the project
      - name: Install NDK
        run: sdkmanager "ndk;27.1.12297006" "cmake;3.22.1"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build gl4es
        run: bash build_scripts/build_gl4es.sh

      - name: Build Ikemen GO Shared Lib
        run: bash build_scripts/build_ikemengo_android.sh

      - name: Install NPM Dependencies
        working-directory: ./app_android
        run: npm ci

      - name: Build APK
        working-directory: ./app_android/android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Zip APK
        if: success() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
        run: |
          zip app-debug.zip app_android/android/app/build/outputs/apk/debug/app-debug.apk
          ls -lh app-debug.zip

      - name: Upload Zipped APK to Telegram (Large File Support)
        if: success() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_STRING_SESSION: ${{ secrets.TELEGRAM_STRING_SESSION }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          pip3 install telethon
          python3 build_scripts/telegram_stuff/upload_to_telegram.py --file app-debug.zip

#       - name: Upload APK
#         uses: actions/upload-artifact@v4
#         with:
#           name: ikemen-go-android
#           path: app_android/android/app/build/outputs/apk/debug/app-debug.apk
#           retention-days: 1
